spring:
  cloud:
    stream:
      bindings:
        order-input-channel:
          destination: outage
        order-outage-output-channel:
          destination: outage

      kafka:
        streams:
          binder:
             brokers: localhost:9092
   
    
        

