---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ksql
  name: ksql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ksql
  template:
    metadata:
      labels:
        app: ksql
    spec:
      containers:
      - env:
        - name: KSQL_BOOTSTRAP_SERVERS
          value: PLAINTEXT://broker-kafka-bootstrap:9092
        - name: KSQL_LISTENERS
          value: http://0.0.0.0:8088
        - name: KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE
          value: "true"
        - name: KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE
          value: "true"
        image: confluentinc/ksqldb-server:0.19.0
        imagePullPolicy: IfNotPresent
        name: ksqldb-server
        ports:
        - containerPort: 8088
          protocol: TCP
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 750Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ksql
  name: ksql
spec:
  ports:
  - port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
    app: ksql
  type: ClusterIP
